# Generated by Django 4.0.4 on 2022-09-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('zona', models.IntegerField(verbose_name='Zona')),
                ('secao', models.IntegerField(verbose_name='Seção')),
                ('escola', models.CharField(max_length=200, null=True, verbose_name='Escola')),
                ('localidade', models.CharField(max_length=100, null=True, verbose_name='Escola')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
