# Generated by Django 4.0.4 on 2022-09-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoa_secao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='localidade',
            field=models.CharField(max_length=100, null=True, verbose_name='Localidade'),
        ),
    ]
