# Generated by Django 4.0.4 on 2022-09-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_escola_remove_pessoa_escola_remove_pessoa_localidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='zona',
            field=models.IntegerField(default=78, verbose_name='Zona'),
        ),
    ]
