# Generated by Django 4.0.4 on 2022-10-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoas", "0009_alter_pessoa_zona"),
    ]

    operations = [
        migrations.CreateModel(
            name="Postulante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=500, unique=True, verbose_name="Nome"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(verbose_name="Quantidade")),
                (
                    "postulante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultado",
                        to="pessoas.postulante",
                        verbose_name="Postulante",
                    ),
                ),
                (
                    "secao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultado",
                        to="pessoas.secao",
                        verbose_name="Seção",
                    ),
                ),
            ],
        ),
    ]
