# Generated by Django 4.0.4 on 2022-05-16 22:07

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cursos', '0006_alter_curso_carga_horaria_alter_turma_valor_lanche_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.CheckConstraint(
                check=models.Q(('dt_fim__gte', django.db.models.expressions.F('dt_inicio'))), name='dt_fim_greater'),
        ),
    ]
