# Generated by Django 4.0.4 on 2022-05-17 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cursos', '0007_turma_dt_fim_greater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='nome',
        ),
    ]
