# Generated by Django 4.0.4 on 2022-05-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cursos', '0008_remove_turma_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='has_aula',
            field=models.BooleanField(default=False, verbose_name='Houve aula?'),
        ),
    ]
