# Generated by Django 4.0.4 on 2022-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cursos', '0009_alter_frequencia_has_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciaaluno',
            name='presente',
            field=models.BooleanField(default=False, help_text='O aluno estava presente?'),
        ),
    ]
