# Generated by Django 4.0.4 on 2022-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cursos', '0010_alter_frequenciaaluno_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='has_aula',
            field=models.BooleanField(default=True, verbose_name='Houve aula?'),
        ),
    ]
