# Generated by Django 4.0.4 on 2022-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_frequencia_has_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciaaluno',
            name='presente',
            field=models.BooleanField(default=False),
        ),
    ]
