# Generated by Django 4.0.4 on 2022-07-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_frequenciaaluno_presente'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_disponivel',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
